# Generated by Django 3.0.5 on 2020-04-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnoBUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnoB_Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnoBUser.EnoB_user', verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': 'EnoB 게시글',
                'verbose_name_plural': 'EnoB 게시글',
                'db_table': 'EonB_Board',
            },
        ),
    ]
