# Generated by Django 3.0.5 on 2020-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnoBBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enob_board',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
