# Generated by Django 3.0.5 on 2020-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnoB_user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='사용자이메일')),
                ('password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('username', models.CharField(max_length=32, verbose_name='사용자이름')),
                ('phone', models.CharField(max_length=32, verbose_name='사용자번호')),
                ('birth', models.IntegerField(verbose_name='사용자생일')),
                ('sex', models.CharField(max_length=16, verbose_name='성별')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': 'EnoB 사용자',
                'verbose_name_plural': 'EnoB 사용자',
                'db_table': 'EnoB_User',
            },
        ),
    ]
