# Generated by Django 3.0.5 on 2020-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnoBUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enob_user',
            name='birth',
            field=models.CharField(max_length=32, verbose_name='사용자생일'),
        ),
    ]
